services:
  targets-navigator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: targets-navigator-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.targets-navigator.rule=Host(`targets.srv903155.hstgr.cloud`)"
      - "traefik.http.routers.targets-navigator.entrypoints=websecure"
      - "traefik.http.routers.targets-navigator.tls.certresolver=letsencrypt"
      - "traefik.http.services.targets-navigator.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"

networks:
  traefik:
    external: true
