# Prometheus configuration for Targets Navigator monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Targets Navigator application
  - job_name: "targets-navigator"
    static_configs:
      - targets: ["targets-navigator:80"]
    metrics_path: "/metrics"
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx metrics (if nginx-prometheus-exporter is available)
  - job_name: "nginx"
    static_configs:
      - targets: ["targets-navigator:9113"]
    scrape_interval: 30s
    scrape_timeout: 10s

  # Docker daemon metrics (if available)
  - job_name: "docker"
    static_configs:
      - targets: ["host.docker.internal:9323"]
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node exporter (if available)
  - job_name: "node"
    static_configs:
      - targets: ["host.docker.internal:9100"]
    scrape_interval: 30s
    scrape_timeout: 10s
